# enable 256-colour and true-colour (24-bit)
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-colour

# Remap

#unbind r
#bind r refresh-client -S

# Functionality
set -g set-clipboard on
set -g detach-on-destroy off
set -g escape-time 0 # remove delay from existing insert mode
set -g history-limit 1000000 #increase history from 2k
set -g mouse on
set -g status-interval 5 #update the status bar every 5 seconds
set -g allow-passthrough on # allow programs in the pane to bypass tmux

# Styling
set -g status-position top
set -g status-left-length 100
# set -g status-style "fg=${fg_bright},bg=${bg}"
set -g status-left "#[bold]  #S "
set -g window-status-format " #I:#W"
set -g window-status-current-format " #[bold,underscore]#I:#W"


# set -g message-style "fg=${gray_light},bg=default"
# set -g mode-style "fg=${gray_dark},bg=${blue_muted}"
# set -g pane-border-style "fg=${gray_dark}"
# set -g pane-active-border-style "fg=${gray_medium}"

# Resurrect
# set -g @resurrect-capture-pane-contents "on"

